language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
      env: NIGHLTY=true
  allow_failures:
    - php: 5.6
    - php: nightly

install:
  - composer clear-cache
  - composer install
  
script:
  - ./vendor/bin/phpcs

notifications:
  email: false
