language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/phan-ast/build

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.3
    - php: 8.3
      env: PHAN=true
      env: PHPCS=true
    - php: nightly
      env: NIGHLTY=true
  allow_failures:
    - php: 5.6
    - php: nightly

before_script:
  - if [[ "$(phpenv version-name)" > 7.0 ]]; then composer install --no-progress --prefer-source; fi

script:
  - if [[ $PHPCS == "true" ]]; then vendor/bin/phpcs --standard=./phpcs.dist.xml; fi
  - if [[ $PHAN == "true" ]]; then vendor/bin/phan --allow-polyfill-parser; fi

notifications:
  email: false
