language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env:
        - COVERAGE=true
        - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
    - php: 7.3
    - php: nightly
      env: NIGHLTY=true
  allow_failures:
    - php: nightly
    - php: 7.0

install:
  - composer clear-cache
  - composer update
  - if [[ $NIGHLTY == true ]]; then composer require "phpunit/phpunit:^8"; fi
  
script:
#  - vendor/bin/phpcs --config-set installed_paths "../../wp-coding-standards/wpcs/,../../automattic/phpcs-neutron-standard/,../../inpsyde/php-coding-standards/,../../wimg/php-compatibility/,../../pheromone/phpcs-security-audit/Security/"
#  - vendor/bin/phpcs -n
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_script:
  - if [[ $COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
  - wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.xml;

notifications:
  email: false
