language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
      env: PHPSTAN=true
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
      env: NIGHLTY=true
  allow_failures:
    - php: 5.6
    - php: nightly

before_script:
  - if [[ $PHPSTAN == "true" ]]; then find . \( -name '*.php' \) -exec php -l {} \; composer install --no-progress --prefer-source; fi

script:
  - vendor/bin/phpcs -n
  - if [[ $PHPSTAN == "true" ]]; then composer require --dev phpstan/phpstan && vendor/bin/phpstan analyse src --level=0 --configuration=phpstan.neon; fi

notifications:
  email: false
