language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
      env: PHPSTAN=true
    - php: 7.1
      env: PHPCS=true
    - php: 7.3
      env: PHAN=true
    - php: nightly
      env: NIGHLTY=true
  allow_failures:
    - php: 5.6
    - php: nightly

before_script:
#  - if [[ $PHPSTAN == "true" ]]; then composer require --dev phpstan/phpstan; fi
#  - if [[ $PHAN == "true" ]]; then find . -name '*.php' -not -path './vendor*' | grep -v test > filelist.txt; fi
  - composer install --no-progress --prefer-source

script:
#  - if [[ $PHPCS == "true" ]]; then vendor/bin/phpcs --config-set installed_paths "../../wp-coding-standards/wpcs/,../../automattic/phpcs-neutron-standard/,../../inpsyde/php-coding-standards/,../../wimg/php-compatibility/"; fi
  - if [[ $PHPCS == "true" ]]; then vendor/bin/phpcs --standard=./phpcs.dist.xml; fi
#  - if [[ $PHPSTAN == "true" ]]; then vendor/bin/phpstan analyse . --level=0 --configuration=phpstan.neon; fi
  - if [[ $PHAN == "true" ]]; then vendor/bin/phan --allow-polyfill-parser; fi

notifications:
  email: false
