language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
      env: NIGHLTY=true
  allow_failures:
    - php: nightly

install:
  - composer clear-cache
  - composer install
  
script:
  - vendor/bin/phpcs --config-set installed_paths "../../wp-coding-standards/wpcs/,../../automattic/phpcs-neutron-standard/,../../inpsyde/php-coding-standards/,../../wimg/php-compatibility/,../../pheromone/phpcs-security-audit/Security/"
  - vendor/bin/phpcs

notifications:
  email: false
